### ISSUE TITLE
License information is a little obscure

### ISSUE THREAD

**Issue by jroweboy** [3Hren/blackhole#177]
Typically, open source projects like to put the licensing information in an easy to find spot because this is one of the most important things to know during the vetting process. I noticed that you have a license in https://github.com/3Hren/blackhole/blob/master/debian/copyright but its kinda hard to tell if this license applies to the entire project or just the debian folder stuff. I'd greatly appreciate it if there was a license file at the root of the repository to clarify what the project license is.

Thanks for all the work on making a good logging library for cpp :)

**Comment by solvingj** [comment]
I was also just looking for this. I suggest just adding a filenamed `LICENSE` to the root.

**Comment by 3Hren** [comment]
I have no idea why it's disappeared. Will republish when PR checks pass.

**Comment by andrusha97** [comment]
So now it's MIT in the root dir and 2-clause BSD in debian?
