### ISSUE TITLE
How to force blackhole to 'reinit' sink?

### ISSUE THREAD

**Issue by bioothod** [3Hren/blackhole#39]
The simplest example is to reinit file sink after file has been moved/deleted.

What methods shoud I use, is there any doc or example on that?

**Comment by 3Hren** [comment]
Nohow.
Logger sinks are meant to be as most independent from the outer world as possible. In your case you should use file sink with move watcher, which reopens a file automatically each time it has been moved/deleted.

The Type is:
```c++
sink::files_t<
    sink::files::boost_backend_t,
    sink::rotator_t<
        sink::files::boost_backend_t,
        sink::rotation::watcher::move_t
    >
>
```

You only need to add the following line into the sink's config:
```
"rotation": {"move": true }
```

If you need to change any sink's configuration in runtime, the only way to do it is to replace the logger object itself, hopefully, it is movable and thread-safe by default.

**Comment by bioothod** [comment]
sink::rotation::watcher is what I need, thank you
