### ISSUE TITLE
error: 'make_unique' is not a member of 'blackhole::utils'

### ISSUE THREAD

**Issue by bioothod** [3Hren/blackhole#43]
Compilation error with swarm package, please take a look at https://groups.google.com/forum/#!topic/reverbrain/N0_4Ns-9RoM

It would be great if you reply in maillist too

**Comment by 3Hren** [comment]
Use v2, Luke.

https://github.com/3Hren/blackhole/blob/v0.2/src/blackhole/utils/unique.hpp
