### ISSUE TITLE
[Feature] %zu length specifier

### ISSUE THREAD

**Issue by abudnik** [3Hren/blackhole#48]
... and other C99 printf format specifiers

http://www.cplusplus.com/reference/cstdio/printf/
http://en.wikipedia.org/wiki/Printf_format_string#Format_placeholders

**Comment by 3Hren** [comment]
Actually that behavior was inherited from `boost::format`, cause we're using it.

I have plans to get rid of `boost::format` in favor of `cppformat` or something more appropriate.

**Comment by 3Hren** [comment]
Blackhole v1.0 will borrow cppformat behavior. Stay tuned.

**Comment by 3Hren** [comment]
1.0 is in alpha stage. You can check. There are a lot of formatting additions/changes.

**Comment by abudnik** [comment]
Cool! Thanks!
