### ISSUE TITLE
Performance optimization for multi-threaded applications

### ISSUE THREAD

**Issue by abudnik** [3Hren/blackhole#51]
Elliptics server node writes logs to /dev/null in our load test stand.
If log level is "debug", then 8k rps processed, but if log level is "error", then elliptics server node can process up to 100k rps.
Elliptics writes to logs from multiple threads. Blackhole has many lock waits. This lock offers critical section in which called write of a single message to log sink.

>sudo strace -f -p `pidof dnet_ioserv` 2> trace2

This log (trace2) contains many records like this:
>[pid 15786] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)

If log level is "error", then log has much less EAGAIN on mutex comparing to "debug" log level.

**Comment by 3Hren** [comment]
I've done userspace RCU logic in 1.0 for the root logger. Writing to files still requires locking.

**Comment by 3Hren** [comment]
About 1.8kk RPS on MacBook Pro i7 2.3Gz for formatting strings and writing it to files.
About 18kk RPS if filtering failed.
