### ISSUE TITLE
BLACKHOLE_HAVE_AT_LEAST_GCC46 isn't correctly set on gcc5+

### ISSUE THREAD

**Issue by bacek** [3Hren/blackhole#57]
Define BLACKHOLE_HAVE_AT_LEAST_GCC46 determines which includes should be used. And it's not correctly set on gcc5.

**Comment by 3Hren** [comment]
Should I cherry-pick this one for a specific version?

**Comment by bacek** [comment]
I'm using 0.2.3, but I already fixed it locally.

**Comment by 3Hren** [comment]
Okay, also fixed here: https://github.com/3Hren/blackhole/commit/0fa9351e58b98233cfcf9a5fb22d35bc8df921b7
